[project]
name = "claude-experiments"
version = "0.1.1"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "pydantic-settings>=2.10.1",
    "loguru>=0.7.2",
    "pymongo>=4.0.0",
    "pydantic>=2.0.0",
]
